# Generated by Django 3.2 on 2023-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthDomain',
            fields=[
                ('name_hash', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('domain_name', models.TextField()),
                ('registrant', models.CharField(max_length=64)),
                ('expiration_date', models.DateTimeField()),
                ('cost', models.BigIntegerField()),
                ('tx_block', models.IntegerField()),
                ('tx_hash', models.CharField(max_length=128)),
                ('tx_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'eth_domain',
                'managed': True,
            },
        ),
    ]
