# Generated by Django 3.2 on 2023-03-30 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthDomain',
            fields=[
                ('node', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('domain_name', models.TextField()),
                ('token_id', models.TextField()),
            ],
            options={
                'db_table': 'eth_domain',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DomainTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_contract_address', models.CharField(max_length=64)),
                ('buyer', models.CharField(max_length=64)),
                ('seller', models.CharField(max_length=64)),
                ('eth_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('weth_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('usdc_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('dai_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('spot_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('tx_block', models.IntegerField()),
                ('tx_hash', models.CharField(max_length=128)),
                ('tx_hash_index', models.CharField(max_length=16)),
                ('tx_dt', models.DateTimeField()),
                ('gas_used', models.BigIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.ethdomain')),
            ],
            options={
                'db_table': 'domain_transfer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DomainRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.TextField()),
                ('expiration_date', models.DateTimeField()),
                ('cost', models.BigIntegerField()),
                ('tx_block', models.IntegerField()),
                ('tx_hash', models.CharField(max_length=128)),
                ('tx_hash_index', models.CharField(max_length=16)),
                ('tx_dt', models.DateTimeField()),
                ('gas_used', models.BigIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.ethdomain')),
            ],
            options={
                'db_table': 'domain_renewal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DomainRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant', models.CharField(max_length=64)),
                ('expiration_date', models.DateTimeField()),
                ('cost', models.BigIntegerField()),
                ('tx_block', models.IntegerField()),
                ('tx_hash', models.CharField(max_length=128)),
                ('tx_hash_index', models.CharField(max_length=16)),
                ('tx_dt', models.DateTimeField()),
                ('gas_used', models.BigIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.ethdomain')),
            ],
            options={
                'db_table': 'domain_registration',
                'managed': True,
            },
        ),
    ]
