# Generated by Django 3.2 on 2023-04-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='domainregistration',
            constraint=models.UniqueConstraint(fields=('tx_hash', 'tx_hash_index'), name='unique_registration'),
        ),
        migrations.AddConstraint(
            model_name='domainrenewal',
            constraint=models.UniqueConstraint(fields=('tx_hash', 'tx_hash_index'), name='unique_renewal'),
        ),
        migrations.AddConstraint(
            model_name='domainsale',
            constraint=models.UniqueConstraint(fields=('tx_hash', 'tx_hash_index'), name='unique_sale'),
        ),
        migrations.AddConstraint(
            model_name='domaintransfer',
            constraint=models.UniqueConstraint(fields=('tx_hash', 'tx_hash_index'), name='unique_transfer'),
        ),
    ]
