# Generated by Django 3.2 on 2023-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_alter_ethdomain_name_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hash', models.CharField(max_length=128)),
                ('domain_name', models.TextField()),
                ('expiration_date', models.DateTimeField()),
                ('cost', models.BigIntegerField()),
                ('tx_block', models.IntegerField()),
                ('tx_hash', models.CharField(max_length=128)),
                ('tx_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'domain_renewal',
                'managed': True,
            },
        ),
    ]
